import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const alfaSlab = localFont({
  src: "./fonts/AlfaSlab.ttf",
  variable: "--font-alfa-slab",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dream Home - Rotary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${alfaSlab.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
