import type { Metadata } from "next";

import "./globals.css";
import { alfaSlab, geistSans, humantBold } from "./fonts/fonts.ts";

export const metadata: Metadata = {
  title: "Dream Home - Rotaract",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${alfaSlab.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
